# Generated by Django 4.2.6 on 2024-01-19 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_dietplan_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
