# Generated by Django 4.2.6 on 2024-01-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_dietplan_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietplan',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='note',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
