# Generated by Django 4.2.6 on 2024-02-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_dietplan_options_alter_dietplan_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='dietplan',
            name='tag',
            field=models.ManyToManyField(to='diet.diettag'),
        ),
    ]
