# Generated by Django 4.2.6 on 2024-02-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_diettag_dietplan_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietplan',
            old_name='tag',
            new_name='tags',
        ),
    ]
