# Generated by Django 4.2.6 on 2024-02-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='hobby_owner',
            new_name='owner',
        ),
    ]
