# Generated by Django 4.2.6 on 2024-02-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_rename_hobby_owner_hobby_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='description',
            field=models.TextField(max_length=256),
        ),
    ]
