# Generated by Django 4.2.6 on 2023-10-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_created_on_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
